server:
    port: ${PORT:8080}

spring:
    thymeleaf:
        cache: false

amazon:
  aws:
    access-key-id: ${AWS_ACCESS_KEY_ID}
    access-key-secret: ${AWS_SECRET_ACCESS_KEY}
  s3:
    default-bucket: ${S3_BUCKET_NAME}

#security:
#  oauth2:
#    client:
#      clientId: ${OAUTH2_CLIENT_ID}
#      clientSecret: ${OAUTH2_CLIENT_SECRET}
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me

google:
  recaptcha:
      url: https://www.google.com/recaptcha/api/siteverify
      secret: ${RECAPTCHA_SECRET}
